# Generated by Django 5.0.3 on 2024-04-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_name_user_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificate',
            field=models.URLField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id_image',
            field=models.URLField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='selfie',
            field=models.URLField(default=0),
        ),
    ]
