# Generated by Django 5.0.3 on 2024-04-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_basicuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuser',
            name='date_of_birth',
            field=models.DateField(default='2022-04-14T12:00:00'),
        ),
    ]
