# Generated by Django 5.0.3 on 2024-04-15 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_basicuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicuser',
            name='addres',
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
