# Generated by Django 5.0.3 on 2024-04-15 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_basicuser_addres_alter_basicuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuser',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
