# Generated by Django 5.0.3 on 2024-04-15 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_basicuser_date_of_birth_alter_basicuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicuser',
            name='date_of_birth',
        ),
    ]
