# Generated by Django 5.0.3 on 2024-04-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_basicuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuser',
            name='address',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
