# Generated by Django 5.0.3 on 2024-04-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_basicuser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicuser',
            name='date_of_birth',
        ),
    ]
