# Generated by Django 5.0.3 on 2024-04-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_basicuser_dete_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='dete_of_birth',
            field=models.DateField(auto_now_add=True),
        ),
    ]
