# Generated by Django 5.0.3 on 2024-04-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_basicuser_dete_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
