# Generated by Django 5.0.3 on 2024-04-21 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.DateTimeField(default=datetime.datetime(24, 10, 3, 10, 55))),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
