# Generated by Django 5.0.3 on 2024-04-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_appoienment_booking_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='appointment_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='appointment',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
