# Generated by Django 5.0.3 on 2024-04-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='appointment',
            field=models.DateTimeField(default='yy/mm/dd'),
        ),
    ]
