# Generated by Django 5.0.3 on 2024-04-19 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_nurse_alter_booking_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='appointment',
            field=models.DateTimeField(default=datetime.datetime(24, 10, 3, 10, 55)),
        ),
    ]
